# Generated by Django 4.1.3 on 2023-01-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpost', '0003_imagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='categorymodel',
            old_name='laugage',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='imagemodel',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='category_id',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='category',
            field=models.ManyToManyField(to='webpost.categorymodel'),
        ),
        migrations.DeleteModel(
            name='ReviewModel',
        ),
    ]
