# Generated by Django 4.1.3 on 2023-01-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpost', '0006_rename_imagemodel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhome',
            name='name',
        ),
    ]
