# Generated by Django 4.1.3 on 2023-01-30 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpost', '0007_remove_userhome_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhome',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='user_home'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
