# Generated by Django 4.1.3 on 2023-11-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpost', '0001_squashed_0008_userhome_image_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhome',
            name='image',
            field=models.ImageField(upload_to='user_home'),
        ),
    ]
