# Generated by Django 4.1.3 on 2023-04-14 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpost', '0001_squashed_0008_userhome_image_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categoryName',
        ),
        migrations.AddField(
            model_name='image',
            name='imageName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userhome',
            name='userHomeName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userhome',
            name='image',
            field=models.ImageField(upload_to='user_home'),
        ),
    ]
