# Generated by Django 4.1.3 on 2023-11-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpost', '0010_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description1',
            field=models.TextField(blank=True, default='', verbose_name='description1'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description2',
            field=models.TextField(blank=True, default='', verbose_name='description2'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='description1',
            field=models.TextField(blank=True, default='', verbose_name='description1'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='description2',
            field=models.TextField(blank=True, default='', verbose_name='description2'),
        ),
    ]
