# Generated by Django 4.1.3 on 2023-11-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpost', '0011_alter_category_description1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description2',
            new_name='description_bottom',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description1',
            new_name='description_top',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='imageName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userhome',
            old_name='description2',
            new_name='description_bottom',
        ),
        migrations.RenameField(
            model_name='userhome',
            old_name='description1',
            new_name='description_top',
        ),
        migrations.RenameField(
            model_name='userhome',
            old_name='userHomeName',
            new_name='name',
        ),
    ]
