# Generated by Django 4.1.3 on 2023-11-08 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpost', '0012_rename_description2_category_description_bottom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_home')),
                ('name', models.CharField(max_length=100)),
                ('description_top', models.TextField(blank=True, default='', verbose_name='description_top')),
                ('description_bottom', models.TextField(blank=True, default='', verbose_name='description_bottom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='description_bottom',
            field=models.TextField(blank=True, default='', verbose_name='description_bottom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_top',
            field=models.TextField(blank=True, default='', verbose_name='description_top'),
        ),
        migrations.DeleteModel(
            name='UserHome',
        ),
    ]
